import { Test, TestingModule } from '@nestjs/testing';
import { CompanyController } from './company.controller';
import { RegisterCompanyUseCase } from '../../application/use-cases/register-company.use-case';
import { GetCompaniesJoinedLastMonthUseCase } from '../../application/use-cases/get-companies-joined-last-month.use-case';
import { GetCompaniesWithTransfersLastMonthUseCase } from '../../application/use-cases/get-companies-with-transfers-last-month.use-case';

describe('CompanyController (autogenerated + fixed)', () => {
  let controller: CompanyController;

  // Mocks para los casos de uso
  const mockRegisterCompany = { execute: jest.fn() };
  const mockGetCompaniesJoinedLastMonth = { execute: jest.fn() };
  const mockGetCompaniesWithTransfersLastMonth = { execute: jest.fn() };

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      controllers: [CompanyController],
      providers: [
        { provide: RegisterCompanyUseCase, useValue: mockRegisterCompany },
        {
          provide: GetCompaniesJoinedLastMonthUseCase,
          useValue: mockGetCompaniesJoinedLastMonth,
        },
        {
          provide: GetCompaniesWithTransfersLastMonthUseCase,
          useValue: mockGetCompaniesWithTransfersLastMonth,
        },
      ],
    }).compile();

    controller = module.get<CompanyController>(CompanyController);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });
});
